include ./themes/darker-rose-pine.conf

shell_integration no-rc no-cursor
confirm_os_window_close 0
cursor_shape block
cursor_text_color #e0def4
font_family family="JetBrains Mono NL" features=""
font_size 14

initial_window_height 700
initial_window_width 1200
remember_window_size yes

tab_title_template "{tab.active_oldest_exe}"

# cursor_trail 5

map ctrl+shift+t new_tab_with_cwd
